[package]
name = "Counter"
version = "1.0.0"
authors = []

[addresses]
count = "0x1bcaee95ba8474d07f1f678b920d309f8d62722d9aa3e48d6f94ae35d8e49e77"
std = "0x1"
[dev-addresses]

[dependencies.MoveStdlib]
git = "https://github.com/move-language/move.git"
rev = "main"
subdir = "language/move-stdlib"

[dev-dependencies]